name: CI local

on: [push]

env:
    DB_HOST: 127.0.0.1
    DB_USER: root
    DB_PASSWORD: root
    DB_NAME: todolist_db
    PORT: 3000
    NODE_ENV: test

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: todolist_db
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
                    --health-interval=5s
                    --health-timeout=5s
                    --health-retries=20
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup node 18
              uses: actions/setup-node@v4
              with: 
                node-version: "18"
                cache: "npm"

            - name: install dependencies
              run: npm install
            
            - name: Test
              run: npm test